<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\images\Cart.jpg" />
    <None Include="wwwroot\images\logo1.png" />
    <None Include="wwwroot\images\z5681897645430_2dd02783d3038beb3dd4deaa21865ea7.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DinkToPdf" Version="1.0.8" />
    <PackageReference Include="Google.Apis.Auth" Version="1.68.0" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.68.0.3427" />
    <PackageReference Include="itext7" Version="7.2.0" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="8.0.5" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="MailKit" Version="4.8.0" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.6" />
    <PackageReference Include="PayPal" Version="1.9.1" />
    <PackageReference Include="PayPalCheckoutSdk" Version="1.0.4" />
    <PackageReference Include="Pdf2Text" Version="1.0.0" />
    <PackageReference Include="Portable.BouncyCastle-Signed" Version="1.7.0.2" />
  </ItemGroup>

</Project>
